### ISSUE TITLE
Offer static library without AFNetworking bundled

### ISSUE THREAD

**Issue by jjxtra** [snaptee/SnapteeSDK-iOS-Example#3]
I want to choose what version of AFNetworking I use. I would prefer a version of the static library without AFNetworking bundled.

**Comment by adi-li** [comment]
Which version do you want to use?
Our current version didn't include AFNetworking in our static library.
Can you give me some details about the issue you're facing in Xcode?

**Comment by jjxtra** [comment]
I get linker errors with duplicate symbols showing AFNetworking in the
libSnapteeSDKLibrary.a. I was able to strip them out using some tools but
it took a while. Would be nice if it just didn't have AFNetworking in the
first place.

-- Jeff

**Comment by adi-li** [comment]
Are you using our static library in our master branch?
Our example also included AFNetworking in the project as well as the libSnapteeSDKLibrary.a, and didn't get linker errors.
Can you take a look on our example and tell me more details on how you import our SDK and AFNetworking?

**Comment by adi-li** [comment]
@jjxtra, Thanks for providing more details on how you get the error through email.
I will push the fix within today.
