### ISSUE TITLE
Tons of Warnings in xCode

### ISSUE THREAD

**Issue by jjxtra** [snaptee/SnapteeSDK-iOS-Example#6]
I have bitcode enabled, when I try to build with Snaptee added I get these warnings:

warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STRedButton.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STSelectTeeColorButtonView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STUtility.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STTeeDesign.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STViewController.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STShippingAddress.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STShippingCost.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/UIImageView+SPTCoreKit.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STTeePrice.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/SPTAPIRequestDataSerialization.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STFormUtility.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STDesignViewController.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/NSURL+SPTCoreKit.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/SPTFileDownloader.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STShoppingCart.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STTeeDesigner.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STTeePriceManager.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/NSString+SPTCoreKit.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STTeeViewUtility.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STPaymentWebViewController.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STPaymentGatewayChoicesHelper.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STLocalizationManager.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/SPTHelper.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/SPTNetworkConstants.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STSelectTeeColorButtonTapArea.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STTextButton.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STSelectTeeColorButtonBgView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STSelectBoxButton.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/SnapteeSDKLibrary.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STLoadingView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STDeliveryInformationViewController.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STCountryPickerTableView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STFileManager.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STAPI.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STSelectClothingView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/SPTNetworkActivityManager.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/SPTCacheManager.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STSelectTeeColorButton.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STPickerTableView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STGATracker.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STOrderViewController.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STTeeView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/NSLocale+SPTCoreKit.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STAffiliateManager.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STTeePreviewView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STPaymentMethodContainerView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STTextField.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STOnboardingView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STClothingObject.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/SPTAPIClient.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STDesignStyle.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STSelectClothingButton.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STSelectionBoxesView.o unable to open object file: No such file or directory
warning: (arm64) /Users/adi/Documents/xcode-workspace/Snaptee/SnapteeSDK/build/SnapteeSDK.build/Release-iphoneos/SnapteeSDKLibrary.build/Objects-normal/arm64/STSaveButton.o unable to open object file: No such file or directory

**Comment by adi-li** [comment]
Thanks for your report.
Please try v1.1.6.1.

**Comment by jjxtra** [comment]
Fixed! Thank you for doing this so fast.
